In [1]:
import os
import pickle
import pandas as pd
import nglview as nv
from IPython.display import display

# =========================
# Paths
# =========================
pdb_dir = "/WAVE/bio/ML/SAE_train/SAEProteinMPNN/evaluation/inputs/"

encodings_path = "/WAVE/bio/ML/SAE_train/SAEProteinMPNN/evaluation/created_data/encodings/output_node_log18_2.pkl"

# =========================
# Load encodings
# =========================
dfs = []

with open(encodings_path, "rb") as f:
    while True:
        try:
            dfs.append(pickle.load(f))
        except EOFError:
            break

encodings = pd.concat(dfs, ignore_index=True)

# =========================
# Clean and parse identifiers
# Example identifier: 1a7wA123
# pdb_id = 1a7w
# chain = A
# residue_idx = 123
# =========================
encodings = encodings.dropna(subset=["identifier"]).copy()
encodings["identifier"] = encodings["identifier"].astype(str)

encodings["pdb_id"] = encodings["identifier"].str[:4]
encodings["chain"] = encodings["identifier"].str[4]

encodings["residue_idx"] = pd.to_numeric(
    encodings["identifier"].str[5:],
    errors="coerce"
)

encodings = encodings.dropna(subset=["residue_idx"]).copy()
encodings["residue_idx"] = encodings["residue_idx"].astype(int)

# =========================
# Get dimension columns
# Your dimensions are numeric columns: 1, 2, 3, ..., 256
# =========================
dimension_cols = [col for col in encodings.columns if isinstance(col, int)]

print("Number of dimensions:", len(dimension_cols))
print("First 10 dimensions:", dimension_cols[:10])

# =========================
# Pick the 5 most active dimensions globally
# =========================
top_5_dims = (
    encodings[dimension_cols]
    .max()
    .sort_values(ascending=False)
    .head(5)
    .index
    .tolist()
)

print("Top 5 dimensions:", top_5_dims)

# =========================
# Visualization function
# =========================
def visualize_top_residues_for_dimension(top10, dim_col):
    for pdb_id in top10["pdb_id"].unique():
        subset = top10[top10["pdb_id"] == pdb_id]

        pdb_path = os.path.join(pdb_dir, f"{pdb_id}.pdb")

        if not os.path.exists(pdb_path):
            print(f"Skipping {pdb_id}: PDB file not found")
            continue

        print(f"\nProtein: {pdb_id}")
        print(f"Dimension: {dim_col}")

        display(subset[["identifier", "pdb_id", "chain", "residue_idx", dim_col]])

        view = nv.show_file(pdb_path, ext="pdb")
        view.clear_representations()

        view.add_cartoon(selection="protein", color="lightgray")

        selections = []

        for _, row in subset.iterrows():
            chain = row["chain"]
            residue = int(row["residue_idx"])
            selections.append(f"resi {residue} and :{chain}")

        selection = " or ".join(selections)

        print("Highlighting:", selection)

        view.add_ball_and_stick(selection=selection, color="red")
        view.add_spacefill(selection=selection, color="red", radiusScale=0.6)

        view.center()

        display(view)

# =========================
# Main loop:
# For each of 5 dimensions,
# find top 10 residues across ALL proteins,
# then visualize those proteins.
# =========================
for dim_col in top_5_dims:
    print("\n" + "=" * 80)
    print(f"TOP 10 RESIDUES FOR DIMENSION {dim_col}")
    print("=" * 80)

    top10 = encodings.nlargest(10, dim_col)

    display(top10[["identifier", "pdb_id", "chain", "residue_idx", dim_col]])

    pdb_path = os.path.join(pdb_dir, "1a7w.pdb")


    visualize_top_residues_for_dimension(top10, dim_col)

Number of dimensions: 256
First 10 dimensions: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Top 5 dimensions: [104, 147, 55, 198, 152]

================================================================================
TOP 10 RESIDUES FOR DIMENSION 104
================================================================================

       identifier pdb_id chain  residue_idx      104
378380   7djmA605   7djm     A          605  3.90918
420791    8s6nD75   8s6n     D           75  3.83184
420926    8s6nG75   8s6n     G           75  3.82950
420548    8s6nA75   8s6n     A           75  3.79776
30553     1oi0A91   1oi0     A           91  3.78139
7892     1dqnA183   1dqn     A          183  3.76733
8122     1dqnB183   1dqn     B          183  3.75763
420665    8s6nB75   8s6n     B           75  3.75554
32648     1po5A50   1po5     A           50  3.75515
101345   2qbxA190   2qbx     A          190  3.75420

Protein: 7djm
Dimension: 104

       identifier pdb_id chain  residue_idx      104
378380   7djmA605   7djm     A          605  3.90918

Highlighting: resi 605 and :A

NGLWidget()

Protein: 8s6n
Dimension: 104

       identifier pdb_id chain  residue_idx      104
420791    8s6nD75   8s6n     D           75  3.83184
420926    8s6nG75   8s6n     G           75  3.82950
420548    8s6nA75   8s6n     A           75  3.79776
420665    8s6nB75   8s6n     B           75  3.75554

Highlighting: resi 75 and :D or resi 75 and :G or resi 75 and :A or resi 75 and :B

NGLWidget()

Protein: 1oi0
Dimension: 104

      identifier pdb_id chain  residue_idx      104
30553    1oi0A91   1oi0     A           91  3.78139

Highlighting: resi 91 and :A

NGLWidget()

Protein: 1dqn
Dimension: 104

     identifier pdb_id chain  residue_idx      104
7892   1dqnA183   1dqn     A          183  3.76733
8122   1dqnB183   1dqn     B          183  3.75763

Highlighting: resi 183 and :A or resi 183 and :B

NGLWidget()

Protein: 1po5
Dimension: 104

      identifier pdb_id chain  residue_idx      104
32648    1po5A50   1po5     A           50  3.75515

Highlighting: resi 50 and :A

NGLWidget()

Protein: 2qbx
Dimension: 104

       identifier pdb_id chain  residue_idx     104
101345   2qbxA190   2qbx     A          190  3.7542

Highlighting: resi 190 and :A

NGLWidget()

================================================================================
TOP 10 RESIDUES FOR DIMENSION 147
================================================================================

       identifier pdb_id chain  residue_idx      147
316432    5t1lD89   5t1l     D           89  3.60321
138838    3fixC12   3fix     C           12  3.59919
292069    5j75A90   5j75     A           90  3.57995
289310    5id0B89   5id0     B           89  3.57750
363749    6u53A89   6u53     A           89  3.57668
292302    5j75B90   5j75     B           90  3.57420
138516    3fixA12   3fix     A           12  3.56788
91178     2ialC80   2ial     C           80  3.55667
289741    5id0D89   5id0     D           89  3.55628
90743     2ialA80   2ial     A           80  3.55594

Protein: 5t1l
Dimension: 147

       identifier pdb_id chain  residue_idx      147
316432    5t1lD89   5t1l     D           89  3.60321

Highlighting: resi 89 and :D

NGLWidget()

Protein: 3fix
Dimension: 147

       identifier pdb_id chain  residue_idx      147
138838    3fixC12   3fix     C           12  3.59919
138516    3fixA12   3fix     A           12  3.56788

Highlighting: resi 12 and :C or resi 12 and :A

NGLWidget()

Protein: 5j75
Dimension: 147

       identifier pdb_id chain  residue_idx      147
292069    5j75A90   5j75     A           90  3.57995
292302    5j75B90   5j75     B           90  3.57420

Highlighting: resi 90 and :A or resi 90 and :B

NGLWidget()

Protein: 5id0
Dimension: 147

       identifier pdb_id chain  residue_idx      147
289310    5id0B89   5id0     B           89  3.57750
289741    5id0D89   5id0     D           89  3.55628

Highlighting: resi 89 and :B or resi 89 and :D

NGLWidget()

Protein: 6u53
Dimension: 147

       identifier pdb_id chain  residue_idx      147
363749    6u53A89   6u53     A           89  3.57668

Highlighting: resi 89 and :A

NGLWidget()

Protein: 2ial
Dimension: 147

      identifier pdb_id chain  residue_idx      147
91178    2ialC80   2ial     C           80  3.55667
90743    2ialA80   2ial     A           80  3.55594

Highlighting: resi 80 and :C or resi 80 and :A

NGLWidget()

================================================================================
TOP 10 RESIDUES FOR DIMENSION 55
================================================================================

       identifier pdb_id chain  residue_idx       55
414201    8hs4A67   8hs4     A           67  3.27026
425257    8xwkD17   8xwk     D           17  3.22927
424511    8xwkA17   8xwk     A           17  3.22576
414438    8hs4B67   8hs4     B           67  3.22318
425008    8xwkC17   8xwk     C           17  3.21510
424760    8xwkB17   8xwk     B           17  3.19420
161224   3mdyA350   3mdy     A          350  3.17898
83135   2fr0A1672   2fr0     A         1672  3.17504
161653   3mdyC350   3mdy     C          350  3.16770
239790   4nstA877   4nst     A          877  3.15124

Protein: 8hs4
Dimension: 55

       identifier pdb_id chain  residue_idx       55
414201    8hs4A67   8hs4     A           67  3.27026
414438    8hs4B67   8hs4     B           67  3.22318

Highlighting: resi 67 and :A or resi 67 and :B

NGLWidget()

Protein: 8xwk
Dimension: 55

       identifier pdb_id chain  residue_idx       55
425257    8xwkD17   8xwk     D           17  3.22927
424511    8xwkA17   8xwk     A           17  3.22576
425008    8xwkC17   8xwk     C           17  3.21510
424760    8xwkB17   8xwk     B           17  3.19420

Highlighting: resi 17 and :D or resi 17 and :A or resi 17 and :C or resi 17 and :B

NGLWidget()

Protein: 3mdy
Dimension: 55

       identifier pdb_id chain  residue_idx       55
161224   3mdyA350   3mdy     A          350  3.17898
161653   3mdyC350   3mdy     C          350  3.16770

Highlighting: resi 350 and :A or resi 350 and :C

NGLWidget()

Protein: 2fr0
Dimension: 55

      identifier pdb_id chain  residue_idx       55
83135  2fr0A1672   2fr0     A         1672  3.17504

Highlighting: resi 1672 and :A

NGLWidget()

Protein: 4nst
Dimension: 55

       identifier pdb_id chain  residue_idx       55
239790   4nstA877   4nst     A          877  3.15124

Highlighting: resi 877 and :A

NGLWidget()

================================================================================
TOP 10 RESIDUES FOR DIMENSION 198
================================================================================

       identifier pdb_id chain  residue_idx      198
258123   4xywA114   4xyw     A          114  2.84872
400838    7xnjB74   7xnj     B           74  2.78314
67729     1zd1B71   1zd1     B           71  2.74489
45904    1t94A515   1t94     A          515  2.71618
368154   6wceA314   6wce     A          314  2.70523
218388    4geqE79   4geq     E           79  2.65404
156279   3kulB899   3kul     B          899  2.65334
83519     2fz6B75   2fz6     B           75  2.64455
20924     1jm0A48   1jm0     A           48  2.63175
371825   6y76A156   6y76     A          156  2.62777

Protein: 4xyw
Dimension: 198

       identifier pdb_id chain  residue_idx      198
258123   4xywA114   4xyw     A          114  2.84872

Highlighting: resi 114 and :A

NGLWidget()

Protein: 7xnj
Dimension: 198

       identifier pdb_id chain  residue_idx      198
400838    7xnjB74   7xnj     B           74  2.78314

Highlighting: resi 74 and :B

NGLWidget()

Protein: 1zd1
Dimension: 198

      identifier pdb_id chain  residue_idx      198
67729    1zd1B71   1zd1     B           71  2.74489

Highlighting: resi 71 and :B

NGLWidget()

Protein: 1t94
Dimension: 198

      identifier pdb_id chain  residue_idx      198
45904   1t94A515   1t94     A          515  2.71618

Highlighting: resi 515 and :A

NGLWidget()

Protein: 6wce
Dimension: 198

       identifier pdb_id chain  residue_idx      198
368154   6wceA314   6wce     A          314  2.70523

Highlighting: resi 314 and :A

NGLWidget()

Protein: 4geq
Dimension: 198

       identifier pdb_id chain  residue_idx      198
218388    4geqE79   4geq     E           79  2.65404

Highlighting: resi 79 and :E

NGLWidget()

Protein: 3kul
Dimension: 198

       identifier pdb_id chain  residue_idx      198
156279   3kulB899   3kul     B          899  2.65334

Highlighting: resi 899 and :B

NGLWidget()

Protein: 2fz6
Dimension: 198

      identifier pdb_id chain  residue_idx      198
83519    2fz6B75   2fz6     B           75  2.64455

Highlighting: resi 75 and :B

NGLWidget()

Protein: 1jm0
Dimension: 198

      identifier pdb_id chain  residue_idx      198
20924    1jm0A48   1jm0     A           48  2.63175

Highlighting: resi 48 and :A

NGLWidget()

Protein: 6y76
Dimension: 198

       identifier pdb_id chain  residue_idx      198
371825   6y76A156   6y76     A          156  2.62777

Highlighting: resi 156 and :A

NGLWidget()

================================================================================
TOP 10 RESIDUES FOR DIMENSION 152
================================================================================

       identifier pdb_id chain  residue_idx      152
273602   5e71A185   5e71     A          185  2.84467
94700    2jjqA276   2jjq     A          276  2.61802
91799     2iftA59   2ift     A           59  2.61383
119441   2yx1A201   2yx1     A          201  2.58679
274496    5egpB52   5egp     B           52  2.57553
119751   2yx1B201   2yx1     B          201  2.57308
274215    5egpA52   5egp     A           52  2.57121
389907   7rc6A162   7rc6     A          162  2.51490
368634    6wlfB57   6wlf     B           57  2.50020
91960     2iftB59   2ift     B           59  2.44549

Protein: 5e71
Dimension: 152

       identifier pdb_id chain  residue_idx      152
273602   5e71A185   5e71     A          185  2.84467

Highlighting: resi 185 and :A

NGLWidget()

Protein: 2jjq
Dimension: 152

      identifier pdb_id chain  residue_idx      152
94700   2jjqA276   2jjq     A          276  2.61802

Highlighting: resi 276 and :A

NGLWidget()

Protein: 2ift
Dimension: 152

      identifier pdb_id chain  residue_idx      152
91799    2iftA59   2ift     A           59  2.61383
91960    2iftB59   2ift     B           59  2.44549

Highlighting: resi 59 and :A or resi 59 and :B

NGLWidget()

Protein: 2yx1
Dimension: 152

       identifier pdb_id chain  residue_idx      152
119441   2yx1A201   2yx1     A          201  2.58679
119751   2yx1B201   2yx1     B          201  2.57308

Highlighting: resi 201 and :A or resi 201 and :B

NGLWidget()

Protein: 5egp
Dimension: 152

       identifier pdb_id chain  residue_idx      152
274496    5egpB52   5egp     B           52  2.57553
274215    5egpA52   5egp     A           52  2.57121

Highlighting: resi 52 and :B or resi 52 and :A

NGLWidget()

Protein: 7rc6
Dimension: 152

       identifier pdb_id chain  residue_idx     152
389907   7rc6A162   7rc6     A          162  2.5149

Highlighting: resi 162 and :A

NGLWidget()

Protein: 6wlf
Dimension: 152

       identifier pdb_id chain  residue_idx     152
368634    6wlfB57   6wlf     B           57  2.5002

Highlighting: resi 57 and :B

NGLWidget()

In [2]:
print(pdb_path)
print(os.path.exists(pdb_path))
print(os.path.getsize(pdb_path))

view = nv.show_file(pdb_path, ext="pdb")
view.clear_representations()
view.add_cartoon(selection="protein", color="lightgray")
view.center()
view

/WAVE/bio/ML/SAE_train/SAEProteinMPNN/evaluation/inputs/1a7w.pdb
True
73467

NGLWidget()